# Generated by Django 3.1 on 2020-08-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('auto_id', models.AutoField(primary_key=True, serialize=False)),
                ('todo', models.CharField(max_length=120)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
