# Generated by Django 3.1 on 2020-08-10 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todos',
            old_name='auto_id',
            new_name='id',
        ),
    ]
